function fig = nexFigure_ephysAtlas(nexObj)
%NEXFIGURE_EPHYSATLAS  Build and attach the Ephys Atlas figure to nexObj.
%
%   Pure layout: creates the uifigure + all widgets, wires callbacks to
%   nexObj public methods, stores structural handles in nexObj.Figure.
%   All state and logic live in nexObj_ephysAtlas.

    c   = nexObj.pal;
    FW  = 960;  FH = 680;  FORE = 52;

    fig = uifigure('Name','Ephys Atlas', ...
        'Position',[80,80,FW,FH], ...
        'Color',c.BG, 'Resize','off', ...
        'CloseRequestFcn',@(~,~) nexObj.closeFcn());

    % ── Forehead ─────────────────────────────────────────────────────────────
    yF = FH - FORE;

    uibutton(fig,'Text','◀','Position',[12,yF+11,30,30], ...
        'BackgroundColor',c.BG,'FontColor',c.FG,'FontSize',15, ...
        'ButtonPushedFcn',@(~,~) nexObj.switchTab(-1));
    uibutton(fig,'Text','▶','Position',[48,yF+11,30,30], ...
        'BackgroundColor',c.BG,'FontColor',c.FG,'FontSize',15, ...
        'ButtonPushedFcn',@(~,~) nexObj.switchTab(+1));

    nexObj.Figure.lblTab = uilabel(fig,'Text','Reference', ...
        'Position',[88,yF+14,170,24], ...
        'FontColor',c.FG,'FontSize',12,'FontWeight','bold', ...
        'BackgroundColor',c.BG);
    nexObj.Figure.subjLbl = uilabel(fig,'Text','—', ...
        'Position',[268,yF+14,300,24], ...
        'FontColor',c.DIM,'FontSize',11,'BackgroundColor',c.BG);

    uipanel(fig,'Position',[0,yF-1,FW,1], ...
        'BackgroundColor',c.SEP,'BorderType','none');

    % ── Tab panels ────────────────────────────────────────────────────────────
    tabPos = [0,0,FW,yF-2];
    nexObj.Figure.tabPanels = { ...
        buildRefTab(fig, tabPos, c, nexObj), ...
        buildIBLTab(fig, tabPos, c, nexObj), ...
        buildPosTab(fig, tabPos, c, nexObj), ...
        buildSesTab(fig, tabPos, c, nexObj)};
    for k = 2:4
        nexObj.Figure.tabPanels{k}.Visible = 'off';
    end
end


function pn = buildRefTab(fig, pos, c, nexObj)
    pn = uipanel(fig,'Position',pos,'BackgroundColor',c.BG,'BorderType','none');
    W = pos(3);  H = pos(4);

    uilabel(pn,'Text','Source','Position',[12,H-38,54,22], ...
        'FontColor',c.DIM,'FontSize',10,'BackgroundColor',c.BG);
    uidropdown(pn,'Tag','refSrcDD','Items',{'Reference'}, ...
        'Position',[70,H-40,224,26], ...
        'BackgroundColor',[0.12 0.12 0.12],'FontColor',c.FG, ...
        'ValueChangedFcn',@(~,~) nexObj.populateRefTable());

    uibutton(pn,'Text','↺','Position',[302,H-40,38,26], ...
        'BackgroundColor',[0.13 0.13 0.13],'FontColor',c.FG,'FontSize',13, ...
        'Tooltip','Re-read atlas HDF5', ...
        'ButtonPushedFcn',@(~,~) nexObj.refreshRefSources());

    uilabel(pn,'Tag','refHint', ...
        'Text','Reference rows are editable.  Phase rows show MAP-assigned raw feature means from recordings.', ...
        'Position',[350,H-38,570,20], ...
        'FontColor',c.DIM,'FontSize',9,'BackgroundColor',c.BG);

    cols = {'Region','ptd µ (ms)','ptd σ','fr µ (Hz)','fr σ','cv µ','cv σ','n','Source'};
    cw   = {80,84,60,84,60,60,56,44,88};
    tbl  = uitable(pn,'Tag','refTable', ...
        'Position',[12,12,W-24,H-56], ...
        'BackgroundColor',c.PNL,'ForegroundColor',c.FG, ...
        'ColumnName',cols,'ColumnWidth',cw, ...
        'ColumnEditable',[false true true true true true true false false], ...
        'RowName',{}, ...
        'CellEditCallback',@(tbl,ev) nexObj.onRefCellEdit(tbl,ev));
    try, tbl.RowStriping = 'off'; catch, end
end


function pn = buildIBLTab(fig, pos, c, nexObj)
    pn = uipanel(fig,'Position',pos,'BackgroundColor',c.BG,'BorderType','none');
    W = pos(3);  H = pos(4);
    LW = 262;  RX = LW+22;  RW = W-RX-12;

    uilabel(pn,'Text','Regions','Position',[12,H-28,LW,20], ...
        'FontColor',c.DIM,'FontSize',10,'BackgroundColor',c.BG);
    lb = uilistbox(pn,'Tag','iblRegionList','Items',{}, ...
        'Position',[12,44,LW,H-74], ...
        'BackgroundColor',c.PNL,'FontColor',c.FG,'Multiselect','on');
    uibutton(pn,'Text','All','Position',[12,12,62,26], ...
        'BackgroundColor',[0.13 0.13 0.13],'FontColor',c.FG, ...
        'ButtonPushedFcn',@(~,~) setListAll_(lb,true));
    uibutton(pn,'Text','None','Position',[80,12,62,26], ...
        'BackgroundColor',[0.13 0.13 0.13],'FontColor',c.FG, ...
        'ButtonPushedFcn',@(~,~) setListAll_(lb,false));

    ctrlH = 162;  ctrlY = H - ctrlH - 10;

    uilabel(pn,'Text','Max sessions','Position',[RX,ctrlY+132,120,18], ...
        'FontColor',c.FG,'FontSize',10,'BackgroundColor',c.BG);
    uispinner(pn,'Tag','iblMaxSess','Value',80,'Step',10,'Limits',[1 999], ...
        'Position',[RX,ctrlY+110,100,26], ...
        'BackgroundColor',[0.12 0.12 0.12],'FontColor',c.FG);
    uicheckbox(pn,'Tag','iblSpontOnly','Text','Spontaneous sessions only', ...
        'Position',[RX,ctrlY+78,260,22],'FontColor',c.FG,'Value',false,'BackgroundColor',c.BG);
    uicheckbox(pn,'Tag','iblFallbackOnly','Text','Literature fallback only', ...
        'Position',[RX,ctrlY+52,260,22],'FontColor',c.FG,'Value',false,'BackgroundColor',c.BG);

    uibutton(pn,'Text','Run IBL Query','Position',[RX,ctrlY+10,148,34], ...
        'BackgroundColor',c.ACC,'FontColor',[1 1 1],'FontWeight','bold', ...
        'ButtonPushedFcn',@(~,~) nexObj.runIBLQuery());
    uibutton(pn,'Text','Stop','Position',[RX+156,ctrlY+10,68,34], ...
        'BackgroundColor',[0.28 0.10 0.10],'FontColor',c.FG, ...
        'ButtonPushedFcn',@(~,~) nexObj.stopIBLQuery());

    uitextarea(pn,'Tag','iblOutput','Value',{'Ready.'}, ...
        'Position',[RX,12,RW,ctrlY-16], ...
        'BackgroundColor',c.BG,'FontColor',c.FG, ...
        'FontSize',10,'FontName','Courier New', ...
        'Editable','off','Scrollable','on');
end


function pn = buildPosTab(fig, pos, c, nexObj)
    pn = uipanel(fig,'Position',pos,'BackgroundColor',c.BG,'BorderType','none');
    W = pos(3);  H = pos(4);
    LW = 200;

    uilabel(pn,'Text','Phase','Position',[12,H-36,50,22], ...
        'FontColor',c.FG,'FontSize',10,'BackgroundColor',c.BG);
    uidropdown(pn,'Tag','posPhaseDD','Items',{'(load atlas)'}, ...
        'Position',[66,H-38,200,26], ...
        'BackgroundColor',[0.12 0.12 0.12],'FontColor',c.FG, ...
        'ValueChangedFcn',@(dd,~) nexObj.populatePosteriors(dd.Value));
    uibutton(pn,'Text','Recompute','Position',[278,H-38,106,26], ...
        'BackgroundColor',[0.13 0.13 0.13],'FontColor',c.FG, ...
        'ButtonPushedFcn',@(~,~) nexObj.recomputePosteriors());
    uilabel(pn,'Tag','posInfo','Text','', ...
        'Position',[396,H-38,360,22], ...
        'FontColor',c.DIM,'FontSize',9,'BackgroundColor',c.BG);

    uilabel(pn,'Text','Channels','Position',[12,H-64,LW,20], ...
        'FontColor',c.DIM,'FontSize',10,'BackgroundColor',c.BG);
    uilistbox(pn,'Tag','posChanList','Items',{}, ...
        'Position',[12,12,LW,H-78], ...
        'BackgroundColor',c.PNL,'FontColor',c.FG, ...
        'ValueChangedFcn',@(lb,~) nexObj.updatePosteriorChart(lb.Value));

    ax = uiaxes(pn,'Position',[LW+28,12,W-LW-44,H-66]);
    ax.Tag = 'posAxes';
    ax.Color = c.PNL;  ax.XColor = c.FG;  ax.YColor = c.FG;
    ax.GridColor = c.DIM;  ax.FontSize = 9;  ax.Box = 'off';
    title(ax,'Select a channel','Color',c.FG,'FontSize',10);
    xlabel(ax,'P(region | channel)','Color',c.FG,'FontSize',9);
end


function pn = buildSesTab(fig, pos, c, nexObj)
    pn = uipanel(fig,'Position',pos,'BackgroundColor',c.BG,'BorderType','none');
    W = pos(3);  H = pos(4);

    uilabel(pn,'Text','Phase','Position',[12,H-36,50,22], ...
        'FontColor',c.FG,'FontSize',10,'BackgroundColor',c.BG);
    uidropdown(pn,'Tag','sesPhaseDD','Items',{'(load atlas)'}, ...
        'Position',[66,H-38,200,26], ...
        'BackgroundColor',[0.12 0.12 0.12],'FontColor',c.FG, ...
        'ValueChangedFcn',@(dd,~) nexObj.populateSessions(dd.Value));
    uilabel(pn,'Tag','sesInfo','Text','', ...
        'Position',[278,H-38,440,22], ...
        'FontColor',c.DIM,'FontSize',9,'BackgroundColor',c.BG);

    tbl = uitable(pn,'Tag','sesTable', ...
        'Position',[12,12,W-24,H-56], ...
        'BackgroundColor',c.PNL,'ForegroundColor',c.FG, ...
        'ColumnName',{'Session','Contributed','n sessions','Last Updated'}, ...
        'ColumnWidth',{240,80,90,180}, ...
        'ColumnEditable',[false false false false], ...
        'RowName',{});
    try, tbl.RowStriping = 'off'; catch, end
end


function setListAll_(lb, allOn)
    if allOn, lb.Value = lb.Items; else, lb.Value = {}; end
end
