function breakoutAxisFields(nexObj, nexPanel, axPtr)
    axFields = fieldnames(axPtr);
    H_panel = nexPanel.ph.Position(4);
    W_panel = nexPanel.ph.Position(3);
    yStep = 25;
    uiHeight = 20;
    m=1;
    H_base = 5;
    for i = 1:length(axFields)
        axField = axFields{i};
        value = axPtr.(axField).value;
        % generate ui spinner
        % Label
        nexPanel.editFields.(axField).Label = uitextarea(nexPanel.ph, ...
            "Value", sprintf("%s", axField), ...
            "Position", [4, H_base + (m+1)*yStep, W_panel*0.95, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);

        % Value spinner
        nexPanel.editFields.(axField).uiField = uispinner(nexPanel.ph, ...
            "Position", [4, H_base + (m+0)*yStep, W_panel*0.8, uiHeight], ...
            "Value", value, ...
            "Step", 1, ...
            "Limits", [-Inf, Inf], ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisPtrChanged(src, event, nexObj, axPtr, axField), ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);

        % Range label
        nexPanel.editFields.(axField).rangeLabel = uitextarea(nexPanel.ph, ...
            "Value", "range", ...
            "Position", [4, H_base + (m-1)*yStep, W_panel*0.95, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);

        % Range start / end spinners
        rStart = axPtr.(axField).range(1);
        rEnd   = axPtr.(axField).range(2);
        nexPanel.editFields.(axField).rangeStart = uispinner(nexPanel.ph, ...
            "Position", [4, H_base + (m-2)*yStep, W_panel*0.45, uiHeight], ...
            "Value", rStart, "Step", 1, "Limits", [1, Inf], ...
            "Tooltip", "Start", ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisRangeChanged(src, event, nexObj, axPtr, axField, 1), ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);
        nexPanel.editFields.(axField).rangeEnd = uispinner(nexPanel.ph, ...
            "Position", [4 + W_panel*0.5, H_base + (m-2)*yStep, W_panel*0.45, uiHeight], ...
            "Value", rEnd, "Step", 1, "Limits", [1, Inf], ...
            "Tooltip", "End", ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisRangeChanged(src, event, nexObj, axPtr, axField, 2), ...
            "FontColor", nexObj.nexon.settings.Colors.cyberGreen);

        H_base = H_base + uiHeight*4 + 10;
    end
end