function breakoutAxisFields(nexObj, nexPanel, axPtr)
    axFields = fieldnames(axPtr);
    W_panel  = nexPanel.ph.Position(3);
    xPad     = 4;
    uiHeight = 20;
    yStep    = 25;
    H_base   = 5;

    % Inline column layout: "Val:" [spn] "Sta:" [spn] "Stp:" [spn] on one row
    lblW = 28;
    spnW = floor((W_panel - xPad - 3*lblW - xPad) / 3);

    for i = 1:length(axFields)
        axField = axFields{i};
        value  = axPtr.(axField).value;
        rStart = axPtr.(axField).range(1);
        rEnd   = axPtr.(axField).range(2);

        % Row 1 (top): axis name label
        nexPanel.editFields.(axField).Label = uitextarea(nexPanel.ph, ...
            "Value",           sprintf("%s", axField), ...
            "Position",        [xPad, H_base + yStep, W_panel*0.95, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);

        % Row 2 (bottom): Val | Sta | Stp on the same Y-level
        xCur = xPad;

        nexPanel.editFields.(axField).valLabel = uitextarea(nexPanel.ph, ...
            "Value",           "Val:", ...
            "Position",        [xCur, H_base, lblW, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);
        xCur = xCur + lblW;

        nexPanel.editFields.(axField).uiField = uispinner(nexPanel.ph, ...
            "Position",        [xCur, H_base, spnW, uiHeight], ...
            "Value",           value, ...
            "Step",            1, ...
            "Limits",          [-Inf, Inf], ...
            "Tooltip",         "Current value", ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisPtrChanged(src, event, nexObj, axPtr, axField), ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);
        xCur = xCur + spnW;

        nexPanel.editFields.(axField).startLabel = uitextarea(nexPanel.ph, ...
            "Value",           "Sta:", ...
            "Position",        [xCur, H_base, lblW, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);
        xCur = xCur + lblW;

        nexPanel.editFields.(axField).rangeStart = uispinner(nexPanel.ph, ...
            "Position",        [xCur, H_base, spnW, uiHeight], ...
            "Value",           rStart, "Step", 1, "Limits", [1, Inf], ...
            "Tooltip",         "Range start", ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisRangeChanged(src, event, nexObj, axPtr, axField, 1), ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);
        xCur = xCur + spnW;

        nexPanel.editFields.(axField).stopLabel = uitextarea(nexPanel.ph, ...
            "Value",           "Stp:", ...
            "Position",        [xCur, H_base, lblW, uiHeight], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);
        xCur = xCur + lblW;

        nexPanel.editFields.(axField).rangeEnd = uispinner(nexPanel.ph, ...
            "Position",        [xCur, H_base, spnW, uiHeight], ...
            "Value",           rEnd, "Step", 1, "Limits", [1, Inf], ...
            "Tooltip",         "Range end", ...
            "BackgroundColor", [0, 0, 0], ...
            "ValueChangedFcn", @(src, event) axisRangeChanged(src, event, nexObj, axPtr, axField, 2), ...
            "FontColor",       nexObj.nexon.settings.Colors.cyberGreen);

        H_base = H_base + yStep * 2 + 5;
    end
end
