function [btnSave, btnLoad] = nexFigure_addSaveLoadControls(parent, mdlObj, rowPos, bgColor, fgColor)
% Build Save | Load buttons for any mdlObj figure, split across rowPos width.
%   rowPos  : [x, y, w, h] — bounding rect the pair occupies (same h as hBtn).
%   bgColor : background colour.
%   fgColor : foreground / text colour.

    x = rowPos(1); y = rowPos(2); w = rowPos(3); h = rowPos(4);
    wHalf = floor((w - 5) / 2);

    btnSave = uibutton(parent, ...
        "Position",        [x, y, wHalf, h], ...
        "Text",            "Save", ...
        "BackgroundColor", bgColor, ...
        "FontColor",       fgColor, ...
        "ButtonPushedFcn", @(~,~) mdlObj.saveFit( ...
            char(datetime("now", "Format", "yyyyMMdd_HHmmss"))));

    btnLoad = uibutton(parent, ...
        "Position",        [x + wHalf + 5, y, wHalf, h], ...
        "Text",            "Load", ...
        "BackgroundColor", bgColor, ...
        "FontColor",       fgColor, ...
        "ButtonPushedFcn", @(~,~) mdlObj.loadFit([]));
end
