function nexFigure_addAvgControls(nexObj, fh, x, y, h)
% Add nBins spinner + Report AVG button pair to a nexFigure top bar.
%   nexObj — nexObject that owns the figure
%   fh     — the uifigure handle
%   x, y   — left edge position of the pair
%   h      — button height (match surrounding controls)
%
% Writes nexObj.Figure.nBinsSpinner and nexObj.Figure.reportAvgButton.
% Total width consumed: 90px (30 spinner + 5 gap + 55 button).

    GREEN = nexObj.nexon.settings.Colors.cyberGreen;
    BLACK = [0 0 0];

    nexObj.Figure.nBinsSpinner = uispinner(fh, ...
        'Position',        [x,    y, 60, h], ...
        'Limits',          [1, 20], ...
        'Value',           4, ...
        'Step',            1, ...
        'BackgroundColor', BLACK, ...
        'FontColor',       GREEN, ...
        'Tooltip',         'nBins — quantile groups for continuous CTG columns');

    nexObj.Figure.reportAvgButton = uibutton(fh, ...
        'Position',        [x+65, y, 75, h], ...
        'BackgroundColor', BLACK, ...
        'FontColor',       GREEN, ...
        'Text',            'Report AVG', ...
        'Tooltip',         'Average STAT by active CTG selection; auto-saves to nexRESULTS.h5', ...
        'ButtonPushedFcn', @(~,~) nexObj.reportAverage([], nexObj.Figure.nBinsSpinner.Value));
end
