function [btn, cbOver, cbTrial] = nexFigure_addTransformControls(parent, mdlObj, rowPos, bgColor, fgColor)
% Build the Transform->DTS button + overwrite/current-trial checkboxes.
%
%   rowPos  : [x, y, w, h] — the same bounding rect the full-width button occupied.
%   bgColor : background colour (e.g. [0 0 0])
%   fgColor : foreground / text colour (e.g. cyberGreen)
%
% Returns btn, cbOver (overwrite), cbTrial (current trial only).
% The button callback reads the checkbox values at click time.

    x = rowPos(1);  y = rowPos(2);
    w = rowPos(3);  h = rowPos(4);

    wBtn = round(w * 0.62);    % ~62 % of row width
    xChk = x + wBtn + 5;
    wChk = w - wBtn - 5;
    hChk = 13;

    btn = uibutton(parent, ...
        "Position",        [x, y, wBtn, h], ...
        "Text",            "Transform->DTS", ...
        "BackgroundColor", bgColor, ...
        "FontColor",       fgColor, ...
        "ButtonPushedFcn", @onTransform);

    cbOver = uicheckbox(parent, ...
        "Position",  [xChk, y + h - hChk - 1, wChk, hChk], ...
        "Text",      "overwrite", ...
        "Value",     false, ...
        "FontColor", fgColor, ...
        "FontSize",  9);

    cbTrial = uicheckbox(parent, ...
        "Position",  [xChk, y + 2, wChk, hChk], ...
        "Text",      "cur trial", ...
        "Value",     false, ...
        "FontColor", fgColor, ...
        "FontSize",  9);

    function onTransform(~, ~)
        mdlObj.scaleApply_transform([], cbOver.Value, cbTrial.Value);
    end
end
