function nexFigure_monoGram(nexObj)
    C = nexObj.nexon.settings.Colors;
    nexObj.Figure.fh = uifigure("Position",[100,1060,1000,830],"Color",[0,0,0]);

    %% Plot panel
    nexObj.Figure.panel0.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[5,5,650,790],"BackgroundColor",[0,0,0]);

    %% Config panels (right column, stacked bottom-up)
    %-- Axis control
    panel5.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[660,5,330,115],"BackgroundColor",[0,0,0],"Scrollable","on");
    nexObj.Figure.panel5 = nexObj_axisPanel(nexObj, nexObj.DF_postOp.ptr, panel5);

    %-- Animation
    panel4.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[660,125,330,100],"BackgroundColor",[0,0,0],"Scrollable","on");
    nexObj.Figure.panel4 = nexObj_cfgPanel_v2(nexObj, nexObj.cfg.aniCfg, panel4, ...
        nexObj.cfg.aniCfg.entryParams, str2func("cfgEntryChanged_v2"), []);

    %-- Visualization
    panel3.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[660,230,330,200],"BackgroundColor",[0,0,0],"Scrollable","on");
    nexObj.Figure.panel3 = nexObj_cfgPanel_v2(nexObj, nexObj.cfg.visCfg, panel3, ...
        nexObj.cfg.visCfg.entryParams, str2func("visCfgEntryChanged_v2"), []);

    %-- Operation
    panel2.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[660,435,330,200],"BackgroundColor",[0,0,0],"Scrollable","on");
    if ~isempty(nexObj.cfg.opCfg)
        nexObj.Figure.panel2 = nexObj_cfgPanel_spinner(nexObj.nexon, nexObj, panel2, ...
            nexObj.cfg.opCfg.entryParams, str2func("opCfgEntryChanged_v2"), []);
    else
        nexObj.Figure.panel2 = panel2;
    end

    %-- Pooling
    panel1.ph = uipanel(nexObj.Figure.fh, ...
        "Position",[660,640,330,155],"BackgroundColor",[0,0,0],"Scrollable","on");
    nexObj.Figure.panel1 = nexObj_poolCfgPanel_v2(nexObj, panel1, str2func("poolCfgEntryChanged"));

    %% UI controls (top bar)
    % Play/pause toggle
    nexObj.Figure.playButton = uibutton("state", ...
        "Parent",           nexObj.Figure.fh, ...
        "Position",         [5,800,25,25], ...
        "BackgroundColor",  [0,0,0], ...
        "Tooltip",          "Play / Pause", ...
        "ValueChangedFcn",  @(~,~) nexObj.startPlayer());

    % Axis-select dropdown — writes to domain.animate via setAnimateAxis
    axKeys = fieldnames(nexObj.DF_postOp.ptr);
    nexObj.Figure.axSelDropDown = uidropdown(nexObj.Figure.fh, ...
        "Position",         [35,800,120,25], ...
        "BackgroundColor",  C.cyberGreen, ...
        "FontColor",        [0,0,0], ...
        "Items",            axKeys, ...
        "Value",            char(nexObj.domain.animate), ...
        "Tooltip",          "Animate axis", ...
        "ValueChangedFcn",  @(src,~) nexObj.setAnimateAxis(src.Value));

    % dfID edit field
    nexObj.Figure.dfIDEditField = uieditfield(nexObj.Figure.fh, ...
        "BackgroundColor",  [0,0,0], ...
        "FontColor",        C.cyberGreen, ...
        "Position",         [850,800,145,25], ...
        "Value",            char(nexObj.dfID_source), ...
        "Tooltip",          "Source dfID", ...
        "ValueChangedFcn",  @(src,event) nexUpdate_dfID(src, event, nexObj.nexon, nexObj));

    % Average button
    nexObj.Figure.reportAvgButton = uibutton(nexObj.Figure.fh, ...
        "Position",         [165,800,25,25], ...
        "BackgroundColor",  [0,0,0], ...
        "Tooltip",          "Report average", ...
        "ButtonPushedFcn",  @(~,~) nexObj.reportAverage([]));

    %% Build initial surf canvas
    nexObj.Figure.panel0.tiles.t  = tiledlayout(nexObj.Figure.panel0.ph, 1, 1);
    nexObj.Figure.panel0.tiles.ax = nexttile(nexObj.Figure.panel0.tiles.t);

    % Slice DF: keep display.rows + display.cols as full range, collapse everything else
    rowKey = nexObj.domain.display.rows;
    colKey = nexObj.domain.display.cols;
    ptr    = nexObj.DF_postOp.ptr;
    Y = nexObj.DF_postOp.ax.(rowKey);
    X = nexObj.DF_postOp.ax.(colKey);
    Z = squeeze(sliceDF(nexObj.DF_postOp.df, ptr, [rowKey, colKey], "range"));
    % Ensure Z is [length(Y) x length(X)] — transpose if dim ordering is inverted
    if ptr.(rowKey).dim > ptr.(colKey).dim
        Z = Z';
    end

    nexObj.Figure.panel0.tiles.graphics.canvas = surf( ...
        nexObj.Figure.panel0.tiles.ax, X, Y, Z, "EdgeColor", "none");
    % view(nexObj.Figure.panel0.tiles.ax, 2);   % flat/image view by default

    % Color map
    load(fullfile(nexObj.nexon.console.BASE.params.paths.repo_path, ...
        "Visualization/RealtimeVis/cmap-cyberGreen.mat"));
    colormap(nexObj.Figure.fh, CT);
    colorAx_green(nexObj.Figure.panel0.tiles.ax);
end
