function nexFigure_waterfall(nexObj)
    C = nexObj.nexon.settings.Colors;

    % Right-column geometry
    xRight = 810;
    wRight = 355;
    wInner = 340;
    xInner = 5;

    % Panel heights
    hAni  = 90;
    hBus  = 250;
    hVis  = 130;
    hWin  = 130;
    gap   = 5;

    % Bottom-to-top Y positions
    yPtr   = xInner;
    yDom   = yPtr  + hBus  + gap;
    yColl  = yDom  + hBus  + gap;
    yVis   = yColl + hBus  + gap;
    yWin   = yVis  + hVis  + gap;
    yAni   = yWin  + hWin  + gap;

    %% Figure
    nexObj.Figure.fh = uifigure( ...
        'Position', [150, 500, 1175, 680], ...
        'Color',    [0, 0, 0]);

    %% panel0 — 3D canvas
    nexObj.Figure.panel0.ph = uipanel(nexObj.Figure.fh, ...
        'Position',        [5, 5, 800, 640], ...
        'BackgroundColor', [0, 0, 0]);
    nexObj.Figure.panel0.tiles.t  = tiledlayout(nexObj.Figure.panel0.ph, 1, 1, ...
        'TileSpacing', 'compact', 'Padding', 'compact');
    nexObj.Figure.panel0.tiles.ax = nexttile(nexObj.Figure.panel0.tiles.t);
    nexObj.Figure.panel0.tiles.graphics = struct();

    ax = nexObj.Figure.panel0.tiles.ax;
    colorAx_green(ax);
    view(ax, -30, 30);
    grid(ax, 'on');

    %% Right scrollable container
    ctrl.ph = uipanel(nexObj.Figure.fh, ...
        'Position',        [xRight, 5, wRight, 640], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on');

    %% aniCfg panel
    entryArgs.entryHeightScaler = 4;
    pan_ani.ph = uipanel(ctrl.ph, ...
        'Position',        [xInner, yAni, wInner, hAni], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on');
    nexObj.Figure.panel_ani = nexObj_cfgPanel_v2(nexObj, nexObj.cfg.aniCfg, pan_ani, ...
        nexObj.cfg.aniCfg.entryParams, str2func("cfgEntryChanged_v2"), entryArgs);

    %% Window / ptr axis panel
    pan_win.ph = uipanel(ctrl.ph, ...
        'Position',        [xInner, yWin, wInner, hWin], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on', ...
        'Title',           'Window', ...
        'ForegroundColor', C.cyberGreen);
    hasPtr = ~isempty(nexObj.DF_postOp) ...
          && isstruct(nexObj.DF_postOp) ...
          && isfield(nexObj.DF_postOp, 'ptr') ...
          && ~isempty(nexObj.DF_postOp.ptr);
    if hasPtr
        nexObj.Figure.windowCfgPanel = nexObj_axisPanel( ...
            nexObj, nexObj.DF_postOp.ptr, pan_win);
    else
        nexObj.Figure.windowCfgPanel = pan_win;
    end

    %% visCfg panel
    pan_vis.ph = uipanel(ctrl.ph, ...
        'Position',        [xInner, yVis, wInner, hVis], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on');
    visCfgChangedFcn = str2func("visCfgEntryChanged_v2");
    nexObj.Figure.panel_vis = nexObj_cfgPanel_v2(nexObj, nexObj.cfg.visCfg, pan_vis, ...
        nexObj.cfg.visCfg.entryParams, visCfgChangedFcn, []);

    %% Collector — View bus (SRC / VW / CLR)
    pan_coll.ph = uipanel(ctrl.ph, ...
        'Position',        [xInner, yColl, wInner, hBus], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on');
    nexObj.Figure.panel_collector = nexObj_listCfgPanel( ...
        nexObj.nexon, pan_coll, nexObj.collector.View, []);
    if isfield(nexObj.collector.View.listBoxes, 'SRC') ...
            && ~isempty(nexObj.collector.View.listBoxes.SRC)
        nexObj.collector.View.listBoxes.SRC.Callback = @(s,~) nexObj.onSRCChanged(s);
    end

    %% Domain bus (D1 max=1, D2 max=1, ANI max=1)
    pan_dom.ph = uipanel(ctrl.ph, ...
        'Position',        [xInner, yDom, wInner, hBus], ...
        'BackgroundColor', [0, 0, 0], ...
        'Scrollable',      'on');
    nexObj.Figure.panel_domain = nexObj_listCfgPanel( ...
        nexObj.nexon, pan_dom, nexObj.collector.Domain, [1, 1, 1]);

    %% Pointer bus
    if ~isempty(nexObj.collector.Pointer)
        pan_ptr.ph = uipanel(ctrl.ph, ...
            'Position',        [xInner, yPtr, wInner, hBus], ...
            'BackgroundColor', [0, 0, 0], ...
            'Scrollable',      'on');
        nexObj.Figure.panel_pointer = nexObj_listCfgPanel( ...
            nexObj.nexon, pan_ptr, nexObj.collector.Pointer, []);
    end

    %% Top-bar controls
    nexObj.Figure.playButton = uibutton('state', ...
        'Parent',           nexObj.Figure.fh, ...
        'Position',         [5, 650, 25, 25], ...
        'BackgroundColor',  [0, 0, 0], ...
        'Tooltip',          'Play / Pause', ...
        'ValueChangedFcn',  @(~,~) nexObj.startPlayer());

    nexObj.Figure.dfIDEditField = uieditfield(nexObj.Figure.fh, ...
        'BackgroundColor', [0, 0, 0], ...
        'FontColor',       C.cyberGreen, ...
        'Position',        [35, 650, 200, 25], ...
        'Value',           char(nexObj.dfID_source), ...
        'ValueChangedFcn', @(src,event) nexUpdate_dfID(src, event, nexObj.nexon, nexObj));

    %% Apply headline and initial visualize
    nexObj.applyHeadline();

    load(fullfile(nexObj.nexon.console.BASE.params.paths.repo_path, ...
        'Visualization/RealtimeVis/cmap-cyberGreen.mat'));
    colormap(nexObj.Figure.fh, CT);

    nexObj.visualize();
end
