function nexFigure_bar(obj)
% Figure for nexObj_bar — a single nested-bar-chart canvas (no tabs).
%
% Layout (960 × 600):
%   Left  (690px) — canvas: one nested bar chart for the active SRC result
%   Right (255px) — SRC panel     (result selector,        uicontrol listbox)
%                   CTG panel     (nesting columns, ordered multi-select)
%                   VW  panel     (row filter,               multi-select)
%                   CLR panel     (per-bar color key(s),      multi-select)
%                   Pointer panel (axis navigation, rebuilt on SRC change)
%
% Uses uifigure (consistent with other nexObject figures). uicontrol
% listboxes are used for SRC/CTG/VW/CLR so the inherited refreshSRC /
% refreshVW / refreshCLR / refreshCTG_bar methods can update
% .String / .Max / .Value directly.

    BLACK = [0 0 0];
    GREEN = resolveGreen(obj);

    fh = uifigure( ...
        'Position',  [200, 200, 960, 600], ...
        'Color',     BLACK, ...
        'Name',      char(obj.headline));
    obj.Figure.fh = fh;
    obj.applyHeadline();

    wRight = 255;
    xRight = 960 - wRight - 5;

    % ── Right sidebar ──────────────────────────────────────────────────────

    % SRC — result selector (single-select, uicontrol for .String API compat)
    pan_src = uipanel(fh, ...
        'Position',        [xRight, 495, wRight, 95], ...
        'BackgroundColor', BLACK, ...
        'Title',           'Result (SRC)', ...
        'ForegroundColor', GREEN);
    lb_src = uicontrol(pan_src, ...
        'Style',           'listbox', ...
        'String',          {}, ...
        'Max',             1, ...
        'Value',           [], ...
        'Units',           'normalized', ...
        'Position',        [0.02 0.05 0.96 0.90], ...
        'BackgroundColor', BLACK, ...
        'ForegroundColor', GREEN, ...
        'FontSize',        9, ...
        'Callback',        @(lb,~) obj.applySRC(lb.String{lb.Value}));
    obj.collector.View.listBoxes.SRC = lb_src;

    % CTG — nesting columns (ordered multi-select: outer tier first)
    pan_ctg = uipanel(fh, ...
        'Position',        [xRight, 410, wRight, 80], ...
        'BackgroundColor', BLACK, ...
        'Title',           'Nesting (CTG)', ...
        'ForegroundColor', GREEN);
    lb_ctg = uicontrol(pan_ctg, ...
        'Style',           'listbox', ...
        'String',          {}, ...
        'Max',             100, ...
        'Value',           [], ...
        'Units',           'normalized', ...
        'Position',        [0.02 0.05 0.96 0.90], ...
        'BackgroundColor', BLACK, ...
        'ForegroundColor', GREEN, ...
        'FontSize',        9, ...
        'Callback',        @(lb,~) onCTGChanged(lb, obj));
    obj.collector.View.listBoxes.CTG = lb_ctg;

    % VW — row filter (multi-select)
    pan_vw = uipanel(fh, ...
        'Position',        [xRight, 325, wRight, 80], ...
        'BackgroundColor', BLACK, ...
        'Title',           'Rows (VW)', ...
        'ForegroundColor', GREEN);
    lb_vw = uicontrol(pan_vw, ...
        'Style',           'listbox', ...
        'String',          {}, ...
        'Max',             100, ...
        'Value',           [], ...
        'Units',           'normalized', ...
        'Position',        [0.02 0.05 0.96 0.90], ...
        'BackgroundColor', BLACK, ...
        'ForegroundColor', GREEN, ...
        'FontSize',        9, ...
        'Callback',        @(~,~) obj.visualize());
    obj.collector.View.listBoxes.VW = lb_vw;

    % CLR — per-bar color key(s) (multi-select; resolveGroupColors handles
    % hierarchical blending when more than one key is selected)
    pan_clr = uipanel(fh, ...
        'Position',        [xRight, 240, wRight, 80], ...
        'BackgroundColor', BLACK, ...
        'Title',           'Color (CLR)', ...
        'ForegroundColor', GREEN);
    lb_clr = uicontrol(pan_clr, ...
        'Style',           'listbox', ...
        'String',          {}, ...
        'Max',             100, ...
        'Value',           [], ...
        'Units',           'normalized', ...
        'Position',        [0.02 0.05 0.96 0.90], ...
        'BackgroundColor', BLACK, ...
        'ForegroundColor', GREEN, ...
        'FontSize',        9, ...
        'Callback',        @(lb,~) onCLRChanged(lb, obj));
    obj.collector.View.listBoxes.CLR = lb_clr;

    % Pointer container — rebuilt by rebuildPointerPanel on SRC change
    pan_ptr = uipanel(fh, ...
        'Position',        [xRight, 5, wRight, 230], ...
        'BackgroundColor', BLACK, ...
        'Title',           'Pointer', ...
        'ForegroundColor', GREEN, ...
        'Scrollable',      'on');
    obj.Figure.ptrContainer = pan_ptr;

    % ── Left: canvas ────────────────────────────────────────────────────────
    wLeft = xRight - 10;
    pan_canvas = uipanel(fh, ...
        'Position',        [5, 5, wLeft, 590], ...
        'BackgroundColor', BLACK);
    obj.Figure.panel0.ph = pan_canvas;
    obj.Figure.panel0.tiles.t = tiledlayout(pan_canvas, 1, 1, ...
        'TileSpacing', 'compact', 'Padding', 'compact');
    ax = nexttile(obj.Figure.panel0.tiles.t);
    obj.Figure.panel0.tiles.ax = ax;
    ax.Color     = BLACK;
    ax.XColor    = GREEN;
    ax.YColor    = GREEN;
    ax.GridColor = GREEN;
    ax.GridAlpha = 0.12;
    ax.Box       = 'on';
    ax.FontSize  = 9;
    grid(ax, 'on');
    hold(ax, 'on');
    ylabel(ax, 'Balanced accuracy', 'Color', GREEN);
end


% ── Helpers ───────────────────────────────────────────────────────────────────

function GREEN = resolveGreen(obj)
    try
        GREEN = obj.nexon.settings.Colors.cyberGreen;
    catch
        GREEN = [0.18 0.8 0.44];
    end
end

function onCTGChanged(lb, obj)
    bus = obj.collector.View;
    bus.selections.CTG = lb.Value;
    obj.visualize();
end

function onCLRChanged(lb, obj)
    bus = obj.collector.View;
    bus.selections.CLR = lb.Value;
    obj.visualize();
end
