function g = nexDraw_error(ax, Z, C_errorBar)
    groups = size(Z,2);
    C = repmat({C_errorBar},1,groups);
    g = [];
    for idx = 1:groups        
        
        x = idx; % horizontal spacing counter
        c = C{idx};

        y = Z(:,idx);
        mu = mean(y, 'omitnan');
        sem = std(y, 'omitnan') / sqrt(numel(y));
        
        % Draw the mean as a point
        plot(ax, x, mu, 'o', ...
            'MarkerFaceColor',c, ...
            'MarkerEdgeColor',c, ...
            'MarkerSize',6);
        
        % Draw SEM bar
        line(ax, ...
            [x x], ...
            [mu-sem mu+sem], ...
            'Color',c, ...
            'LineWidth',1);
        
        % Small horizontal caps
        line(ax, ...
            [x-0.05 x+0.05], ...
            [mu-sem mu-sem], ...
            'Color',c, ...
            'LineWidth',1);
        
        line(ax, ...
            [x-0.05 x+0.05], ...
            [mu+sem mu+sem], ...
            'Color',c, ...
            'LineWidth',1);
    end    
end