function model = model_umap(args)
    % umap_mod = py.importlib.import_module('umap');
    if nargin < 1, args = struct(); end
    model = py.umap.UMAP(pyargs( ...
        'n_components', int32(3), ...
        'n_neighbors',  int32(15), ...
        'min_dist',     0.1 ...
    ));
end
