function poolCfgPanel = nexObj_poolCfgPanel_v3(nexObj, panel, poolCfgEntryChangedFcn)
    nexon = nexObj.nexon;
    % dropdown/spinner combo
    W_panel = panel.ph.Position(3);

    h_button  = 30;
    h_uiField = 20;
    padding   = 5;
    yStep     = h_uiField + padding;

    w_dropdown   = W_panel * 0.5 - padding * 1.5;
    % right half split: divsPerBin | reducerDim
    w_spin_each  = (W_panel * 0.5 - padding * 1.5 - padding) / 2;

    % Resolve pMap
    try
        pMap = nexObj.Origin.pMap;
    catch
        pMap = nexObj.pMap;
    end
    axFields = convertCharsToStrings(fieldnames(pMap));

    % Resize panel to fit all content so Apply button never falls off.
    % Each axis needs 2 rows (label + controls); Add button + margins.
    n_axes   = length(axFields);
    needed_H = n_axes * 2 * yStep + h_button + 3 * padding;
    pos      = panel.ph.Position;
    pos(4)   = max(pos(4), needed_H);
    panel.ph.Position   = pos;
    panel.ph.Scrollable = "on";
    H_panel  = pos(4);

    yPtr = H_panel - padding - h_uiField;

    for i = 1:length(axFields)
        % axField = string(axFields{i});
        axField = axFields(i);
        % poolMap = nexObj.(axField);
        poolMap = pMap.(axField);
        % segOpts = poolCfg.ax.(axField).segOpts;
        segOpts = poolMap.binTypes;
        
        % Label
        uiTextID = sprintf("%s_label", axField);
        panel.(uiTextID) = uitextarea(panel.ph, ...
            "Position", [padding, yPtr, W_panel - 2*padding, h_uiField], ...
            "FontColor", nexon.settings.Colors.cyberGreen, ...
            "BackgroundColor", [0, 0, 0], ...
            "Value", axField);
    
        yPtr = yPtr - yStep;
    
        % Dropdown (left half)
        uiID = sprintf("%s_dropDown", axField);
        panel.(uiID) = uidropdown(panel.ph, ...
            "Items", segOpts, ...
            "Value", segOpts(1), ...
            "Position", [padding, yPtr, w_dropdown, h_uiField], ...
            "BackgroundColor", nexon.settings.Colors.cyberGreen, ...
            "FontColor", [0, 0, 0],...
            "ValueChangedFcn", @(src, event)poolCfgEntryChangedFcn(src, event, poolMap, "binType"));
    
        % divsPerBin spinner (+/- = mean-pool/PCA, Inf = collapse)
        x_spin1 = padding + w_dropdown + padding;
        uiID = sprintf("%s_spinner", axField);
        panel.(uiID) = uispinner(panel.ph, ...
            "Value", poolMap.divsPerBin, ...
            "Position", [x_spin1, yPtr, w_spin_each, h_uiField], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexon.settings.Colors.cyberGreen, ...
            "Limits", [-Inf, Inf], ...
            "Step", 1,...
            "ValueChangedFcn", @(src, event)poolCfgEntryChangedFcn(src, event, poolMap, "divsPerBin"));

        % reducerDim spinner (PCA components per block, used when divsPerBin < 0)
        x_spin2 = x_spin1 + w_spin_each + padding;
        uiID = sprintf("%s_reducerDim", axField);
        panel.(uiID) = uispinner(panel.ph, ...
            "Value", poolMap.reducerDim, ...
            "Position", [x_spin2, yPtr, w_spin_each, h_uiField], ...
            "BackgroundColor", [0, 0, 0], ...
            "FontColor", nexon.settings.Colors.cyberGreen, ...
            "Limits", [1, Inf], ...
            "Step", 1,...
            "ValueChangedFcn", @(src, event)poolCfgEntryChangedFcn(src, event, poolMap, "reducerDim"));
    
        yPtr = yPtr - yStep;
    end
    
    % Apply button (10 units below last element)
    panel.applyPoolButton =  uicontrol(panel.ph, ...
        "Style", "pushbutton", ...
        "String", "", ...
        "Position", [padding, yPtr - 10, W_panel - 2*padding, h_button], ...
        "BackgroundColor", nexon.settings.Colors.cyberGreen, ...
        "ForegroundColor", [0, 0, 0], ...
        "FontWeight", "bold", ...
        "Callback", @(src, event)nexObj.updateScope());

    % return handle
    poolCfgPanel = panel;
    
end